workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.chippin.chippin
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          cd chippin/ios
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd chippin
          flutter packages pub get
      - name: Build IPA
        script: |
          cd chippin
          BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "com.chippin.chippin") + 1))
          flutter build ipa --release \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - chippin/build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - External Testers
      email:
        recipients:
          - goldkazyna@gmail.com
        notify:
          success: true
          failure: true
